export const WsErrorCode = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FINISHED: 'ROOM_FINISHED',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  ROOM_FULL: 'ROOM_FULL',
  KICKED: 'KICKED',
  ROOM_ERROR: 'ROOM_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type WsErrorCode = (typeof WsErrorCode)[keyof typeof WsErrorCode];
